Pig Stack Trace
---------------
ERROR 6000: Output specification 'hdfs://cvrsvc11-ib/users/kbhatia/screening-alex-2' is invalid or already exists

org.apache.pig.impl.plan.PlanValidationException: ERROR 0: An unexpected exception caused the validation to stop
	at org.apache.pig.impl.plan.PlanValidator.validate(PlanValidator.java:56)
	at org.apache.pig.impl.logicalLayer.validators.InputOutputFileValidator.validate(InputOutputFileValidator.java:49)
	at org.apache.pig.impl.logicalLayer.validators.InputOutputFileValidator.validate(InputOutputFileValidator.java:37)
	at org.apache.pig.impl.logicalLayer.validators.LogicalPlanValidationExecutor.validate(LogicalPlanValidationExecutor.java:89)
	at org.apache.pig.PigServer.validate(PigServer.java:930)
	at org.apache.pig.PigServer.compileLp(PigServer.java:910)
	at org.apache.pig.PigServer.compileLp(PigServer.java:871)
	at org.apache.pig.PigServer.compileLp(PigServer.java:852)
	at org.apache.pig.PigServer.execute(PigServer.java:816)
	at org.apache.pig.PigServer.access$100(PigServer.java:105)
	at org.apache.pig.PigServer$Graph.execute(PigServer.java:1080)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:288)
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:109)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:166)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:138)
	at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:89)
	at org.apache.pig.Main.main(Main.java:391)
Caused by: org.apache.pig.impl.plan.PlanValidationException: ERROR 6000: Output specification 'hdfs://cvrsvc11-ib/users/kbhatia/screening-alex-2' is invalid or already exists
	at org.apache.pig.impl.logicalLayer.validators.InputOutputFileVisitor.visit(InputOutputFileVisitor.java:113)
	at org.apache.pig.impl.logicalLayer.LOStore.visit(LOStore.java:140)
	at org.apache.pig.impl.logicalLayer.LOStore.visit(LOStore.java:37)
	at org.apache.pig.impl.plan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:67)
	at org.apache.pig.impl.plan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:69)
	at org.apache.pig.impl.plan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:69)
	at org.apache.pig.impl.plan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:69)
	at org.apache.pig.impl.plan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:69)
	at org.apache.pig.impl.plan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:69)
	at org.apache.pig.impl.plan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:69)
	at org.apache.pig.impl.plan.DepthFirstWalker.walk(DepthFirstWalker.java:50)
	at org.apache.pig.impl.plan.PlanVisitor.visit(PlanVisitor.java:51)
	at org.apache.pig.impl.plan.PlanValidator.validate(PlanValidator.java:50)
	... 16 more
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory hdfs://cvrsvc11-ib/users/kbhatia/screening-alex-2 already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:123)
	at org.apache.pig.impl.logicalLayer.validators.InputOutputFileVisitor.visit(InputOutputFileVisitor.java:96)
	... 28 more
================================================================================
